# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blake's blog stuff
email: Pantheonvi@gmail.com
description: "I'm just kind of doing this,
 learning Ruby right now, putting up what I learn, stuff from exercises and whatnot."

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fluttermedic.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  fluttermedic

# Build settings
markdown: kramdown
